# Generated by Django 6.0.4 on 2026-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=64, unique=True)),
                ("last_hash", models.CharField(blank=True, default="", max_length=64)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Loaded from ERP, not yet sent"),
                            ("SUCCESS", "Successfully sent to e-shop"),
                            ("FAILED", "Failed to send to e-shop"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        help_text="Last transformed payload sent to e-shop",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["sku"],
            },
        ),
    ]
